export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const RESET_ERROR_USER = "RESET_ERROR_USER";
export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAIL = "DELETE_FAIL";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"
export const RESET_UPDATED = "RESET_UPDATED"


export const UPDATE_TRACKING_INFO = "UPDATE_TRACKING_INFO";
export const RESET_TRACKING_SESSION = "RESET_TRACKING_SESSION";
export const LOCATION_ERROR = "LOCATION_ERROR";
export const RESET_LOCATION_ERROR = "RESET_LOCATION_ERROR";
export const SET_TRACKING_ACTIVE = "SET_TRACKING_ACTIVE";
export const SET_TRACKING_INACTIVE = "SET_TRACKING_INACTIVE";
export const START_SESSION = "START_SESSION";
export const REHYDRATE_SESSION_FROM_STORAGE = "REHYDRATE_SESSION_FROM_STORAGE"


export const CHANGE_THEME = "CHANGE_THEME"


export const STATISTICS_FAIL = "STATISTICS_FAIL"
export const STATISTICS_REQUEST = "STATISTICS_REQUEST"
export const STATISTICS_SUCCESS = "STATISTICS_SUCCESS"
export const RESET_STATISTICS_ERROR = "RESET_STATISTICS_ERROR"